#pragma once

#include <cstdint>

enum class EAPIType
{
	API_OPENGL,
	API_VULKAN,
	API_DIRECTX12,
	API_NONE
};

enum class EWindowMode
{
	MODE_WINDOWED,
	MODE_FULLSCREEN,
	MODE_BORDERLESS
};

enum class EAlignment
{
	ALIGN_CENTERED,
	ALIGN_CENTERED_HORIZONTAL,
	ALIGN_CENTERED_VERTICAL,
	ALIGN_TOP_LEFT,
	ALIGN_TOP_RIGHT,
	ALIGN_BOTTOM_LEFT,
	ALIGN_BOTTOM_RIGHT
};

enum class ELoadingState
{
	STATE_LOADING_AWAITING_FROM_DISK,
	STATE_LOADING_FROM_DISK,
	STATE_LOADING_COMPLETE,
};

enum class ETextureState // instead of bake 
{
	TEXTURE_STATE_AWAITING_LOAD,
	TEXTURE_STATE_LOADING,
	TEXTURE_STATE_LOAD_COMPLETE,
	TEXTURE_STATE_UNDEFINED
};

enum class EBlendingMode
{
	BLEND_DISABLED,
	BLEND_ENABLED,
	BLEND_ALPHA_DISCARDED,
	BLEND_HAIR_UNDERLAYER,
	BLEND_HAIR_TOPLAYER,
	BLEND_DO_NOT_RENDER
};

enum class EImageDataType
{
	IMAGE_UNCOMPRESSED,
	IMAGE_COMPRESSED,
	IMAGE_EXR,
	IMAGE_UNDEFINED
};

enum class ETextureWrapMode
{
	TEXTURE_WRAP_REPEAT,
	TEXTURE_WRAP_MIRRORED_REPEAT,
	TEXTURE_WRAP_CLAMP_TO_EDGE,
	TEXTURE_WRAP_CLAMP_TO_BORDER,
	TEXTURE_WRAP_UNDEFINED,
};

enum class ETextureFilterMode
{
	TEXTURE_FILTER_NEAREST,
	TEXTURE_FILTER_LINEAR,
	TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST,
	TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST,
	TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR,
	TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR,
	TEXTURE_FILTER_UNDEFINED
};

enum class EAxis
{
	AXIS_X,
	AXIS_Y,
	AXIS_Z,
	AXIS_UNDEFINED
};

enum class ECameraMode
{
	CAMERA_MODE_FIRST_PERSON,
	CAMERA_MODE_THIRD_PERSON,
	CAMERA_MODE_ORBITAL,
	CAMERA_MODE_UNDEFINED
};

enum class EShadingMode
{
	SHADING_MODE_SHADED,
	SHADING_MODE_WIREFRAME,
	SHADING_MODE_OVERLAY,
	SHADING_MODE_COUNT
};

enum class ECameraView
{
	CAMERA_PRESPECTIVE,
	CAMERA_ORTHOGRAPHIC,
	CAMERA_FRONT,
	CAMERA_BACK,
	CAMERA_LEFT,
	CAMERA_RIGHT,
	CAMERA_TOP,
	CAMERA_BOTTOM,
	CAMERA_UNDEFINED
};

enum class EUniformBufferBindingPoints : uint32_t
{
	UBO_BP_CAMERA = 0,			// Binding point 0 reserved for Camera UBO
	UBO_BP_LIGHTING = 1,
	UBO_BP_MATERIAL = 2,
	UBO_BP_TRANSFORM = 3,
	UBO_BP_ANIMATION = 4,
	UBO_BP_POSTPROCESS = 5,
	UBO_BP_MAX_NUM = 6
};

enum class EShaderStorageBindingPoints : uint32_t
{
	SSBO_BP_TERRAIN,		// Binding point 0 reserved for Terrain SSBO
	SSBO_BP_MAX_NUM,
};