#include "Stdafx.h"
#include "GLUtils.h"
#include "LogManager.h"

GLuint Anubis::GL::CreateBuffer()
{
	GLuint uiBufferID = 0;

	// Create new ID
	if (IsGLVersionHigher(4, 5))
	{
		glCreateBuffers(1, &uiBufferID);
	}
	else
	{
		glGenBuffers(1, &uiBufferID);
	}
	return (uiBufferID);
}

void Anubis::GL::DeleteBuffer(GLuint& uiBufferID)
{
	if (uiBufferID != 0)
	{
		glDeleteBuffers(1, &uiBufferID);
		uiBufferID = 0;
	}
}

GLuint Anubis::GL::CreateVertexArray()
{
	GLuint uiVertexArrayID = 0;

	// Create new ID
	if (IsGLVersionHigher(4, 5))
	{
		glCreateVertexArrays(1, &uiVertexArrayID);
	}
	else
	{
		glGenVertexArrays(1, &uiVertexArrayID);
	}
	return (uiVertexArrayID);
}

void Anubis::GL::DeleteVertexArray(GLuint& uiVertexArrayID)
{
	if (uiVertexArrayID != 0)
	{
		glDeleteVertexArrays(1, &uiVertexArrayID);
		uiVertexArrayID = 0;
	}
}

GLuint Anubis::GL::CreateTexture(GLenum eTextureTarget)
{
	GLuint uiTextureID = 0;

	if (IsGLVersionHigher(4, 5))
	{
		// DSA: No binding required, very efficient
		glCreateTextures(eTextureTarget, 1, &uiTextureID);
	}
	else
	{
		// Legacy: MUST bind to "initialize" the object type in the driver
		glGenTextures(1, &uiTextureID);

		// Use the passed target (eTargetTexture) instead of hardcoded GL_TEXTURE_2D
		glBindTexture(eTextureTarget, uiTextureID);
	}

	return (uiTextureID);
}

void Anubis::GL::DeleteTexture(GLuint& uiTextureID)
{
	if (uiTextureID != 0)
	{
		glDeleteTextures(1, &uiTextureID);
		uiTextureID = 0;
	}
}

/**
 * @brief Creates a single OpenGL texture and returns its ID.
 *
 * Uses glCreateTextures (DSA) on modern drivers or glGenTextures (Legacy)
 * as a fallback to ensure cross-version compatibility.
 *
 * @param uiTextureID Reference to store the created texture ID.
 * @param eTargetTexture The target texture type (e.g., GL_TEXTURE_2D).
 * @return true if the texture was created successfully, false otherwise.
 */
bool Anubis::GL::CreateGLTexture(GLuint& uiTextureID, GLenum eTargetTexture)
{
	// 1. Prevent leaks by cleaning up existing ID
	SafeDeletGLTexture(uiTextureID);

	// 2. Create new ID
	if (IsGLVersionHigher(4, 5))
	{
		// DSA: No binding required, very efficient
		glCreateTextures(eTargetTexture, 1, &uiTextureID);
	}
	else
	{
		// Legacy: MUST bind to "initialize" the object type in the driver
		glGenTextures(1, &uiTextureID);

		// Use the passed target (eTargetTexture) instead of hardcoded GL_TEXTURE_2D
		glBindTexture(eTargetTexture, uiTextureID);
	}

	// 3. Validation
	if (uiTextureID == 0)
	{
		syserr("Core: Failed to generate GL Texture!");
		return (false);
	}

	return (true);
}

/**
 * @brief Safely deletes an OpenGL texture and resets its ID.
 *
 * @param uiTextureID Reference to the texture ID to delete.
 */
void Anubis::GL::SafeDeletGLTexture(GLuint& uiTextureID)
{
	if (uiTextureID)
	{
		glDeleteTextures(1, &uiTextureID);
		uiTextureID = 0;
	}
}

/**
 * @brief Makes a texture handle resident on the GPU for bindless access.
 * * Generates a 64-bit GPU memory handle for the texture and locks it into
 * GPU memory. This allows shaders to access the texture directly via the
 * handle without using glBindTexture.
 * @param uiTextureID The OpenGL ID of the texture to make resident.
 * @param ui64Handle The 64-bit handle generated by the driver.
 * @param bIsResident Set to true if residency was successfully established.
 */
void Anubis::GL::MakeTextureResident(GLuint uiTextureID, GLuint64& ui64Handle, bool& bIsResident)
{
	if (!GLAD_GL_ARB_bindless_texture)
	{
		ui64Handle = 0;
		bIsResident = false;
		syserr("Bindless Textures not supported on this GPU/Driver!");
		return;
	}

	if (!bIsResident)
	{
		// 2. Get the 64-bit GPU address
		// Important: Once a handle is generated for a texture, it is permanent for the life of that texture ID.
		// You don't actually need to get it again if you just want to toggle residency.
		ui64Handle = glGetTextureHandleARB(uiTextureID);
		if (ui64Handle != 0)
		{
			glMakeTextureHandleResidentARB(ui64Handle);
			bIsResident = true;
		}
	}
}

/**
 * @brief Makes a texture handle non-resident and releases the bindless state.
 * Tells the GPU that the texture handle is no longer needed for direct access.
 * This must be called before deleting the texture or changing its storage.
 * @param ui64Handle The 64-bit handle to release. Set to 0 after call.
 * @param bIsResident  Reset to false after the handle is released.
 */
void Anubis::GL::MakeTextureNonResident(GLuint64& ui64Handle, bool& bIsResident)
{
	if (!GLAD_GL_ARB_bindless_texture)
	{
		ui64Handle = 0;
		bIsResident = false;
		return;
	}

	if (bIsResident && ui64Handle != 0)
	{
		// No need to check glIsTextureHandleResidentARB (it's slow)
		// Just tell the driver this handle is no longer in use
		glMakeTextureHandleNonResidentARB(ui64Handle);

		ui64Handle = 0;
		bIsResident = false;
	}
}

/**
 * @brief Uploads texture data to the GPU.
 *
 * Uses Direct State Access (DSA) on modern drivers or legacy binding methods
 * as a fallback to ensure cross-version compatibility.
 *
 * @param uiTextureID Reference to store the created texture ID.
 * @param sImageData The image data to upload to the GPU.
 * @param eTextureTarget The target texture type (e.g., GL_TEXTURE_2D).
 * @param bGenMipMaps Whether to generate mipmaps for the texture.
 * @param sourceType The data type of the source image data (e.g., GL_UNSIGNED_BYTE).
 * @return true if the texture was created and data uploaded successfully, false otherwise.
 */
bool Anubis::GL::UploadTextureDataToGPU(GLuint& uiTextureID, const SImageData& sImageData, GLenum eTextureTarget, bool bGenMipMaps, GLenum sourceType)
{
	if (IsGLVersionHigher(4, 6))
	{
		return (UploadTextureDataToGPUDSA(uiTextureID, sImageData, eTextureTarget, bGenMipMaps, sourceType));
	}
	else
	{
		return (UploadTextureDataToGPULegacy(uiTextureID, sImageData, eTextureTarget, bGenMipMaps, sourceType));
	}
}

/**
 * @brief Uploads texture data to the GPU using legacy binding methods.
 *
 * This function creates a new OpenGL texture using legacy binding methods,
 * uploads the provided image data, and sets texture parameters such as filtering
 * and wrapping. It supports generating mipmaps if requested.
 *
 * @param uiTextureID Reference to store the created texture ID.
 * @param sImageData The image data to upload to the GPU.
 * @param eTextureTarget The target texture type (e.g., GL_TEXTURE_2D).
 * @param bGenMipMaps Whether to generate mipmaps for the texture.
 * @param sourceType The data type of the source image data (e.g., GL_UNSIGNED_BYTE).
 * @return true if the texture was created and data uploaded successfully, false otherwise.
 */
bool Anubis::GL::UploadTextureDataToGPUDSA(GLuint& uiTextureID, const SImageData& sImageData, GLenum eTextureTarget, bool bGenMipMaps, GLenum sourceType)
{
	if (!CreateGLTexture(uiTextureID, eTextureTarget))
	{
		syserr("Failed to create texture for DSA upload!");
		return false;
	}

	// Calculate Mip Levels
	GLint iLevels = 1;
	if (bGenMipMaps && sImageData.iWidth > 0)
	{
		iLevels = static_cast<GLint>(std::floor(std::log2(std::max(sImageData.iWidth, sImageData.iHeight)))) + 1;
	}

	bool bIsFloat = (sourceType == GL_FLOAT);

	if (eTextureTarget == GL_TEXTURE_2D)
	{
		// Reset Swizzle to standard
		GLint defaultSwizzle[] = { GL_RED, GL_GREEN, GL_BLUE, GL_ALPHA };
		glTextureParameteriv(uiTextureID, GL_TEXTURE_SWIZZLE_RGBA, defaultSwizzle);

		// Determine formats based on channel count
		// 3. Determine Formats
		GLenum internalFormat, pixelFormat;
		bool bIsFloat = (sourceType == GL_FLOAT);

		GetGLTextureFormats(sImageData.iChannels, internalFormat, pixelFormat, bIsFloat);

		// 1. Allocate Immutable Storage
		glTextureStorage2D(uiTextureID, iLevels, internalFormat, sImageData.iWidth, sImageData.iHeight);

		// 2. Upload Data - USE sourceType HERE!
		if (sImageData.pData)
		{
			glTextureSubImage2D(uiTextureID, 0, 0, 0, sImageData.iWidth, sImageData.iHeight, pixelFormat, sourceType, sImageData.pData);
		}

		// 3. Handle Grayscale Swizzle
		if (sImageData.iChannels == 1)
		{
			GLint greySwizzle[] = { GL_RED, GL_RED, GL_RED, GL_ONE };
			glTextureParameteriv(uiTextureID, GL_TEXTURE_SWIZZLE_RGBA, greySwizzle);
		}
	}

	// Parameters
	glTextureParameteri(uiTextureID, GL_TEXTURE_MIN_FILTER, iLevels > 1 ? GL_LINEAR_MIPMAP_LINEAR : GL_LINEAR);
	glTextureParameteri(uiTextureID, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
	glTextureParameteri(uiTextureID, GL_TEXTURE_WRAP_S, GL_REPEAT);
	glTextureParameteri(uiTextureID, GL_TEXTURE_WRAP_T, GL_REPEAT);

	if (iLevels > 1 && sImageData.pData)
	{
		glGenerateTextureMipmap(uiTextureID);
	}

	return (true);
}

/**
 * @brief Uploads texture data to the GPU using legacy binding methods.
 *
 * This function creates a new OpenGL texture using legacy binding methods,
 * uploads the provided image data, and sets texture parameters such as filtering
 * and wrapping. It supports generating mipmaps if requested.
 *
 * @param uiTextureID Reference to store the created texture ID.
 * @param sImageData The image data to upload to the GPU.
 * @param eTextureTarget The target texture type (e.g., GL_TEXTURE_2D).
 * @param bGenMipMaps Whether to generate mipmaps for the texture.
 * @param sourceType The data type of the source image data (e.g., GL_UNSIGNED_BYTE).
 * @return true if the texture was created and data uploaded successfully, false otherwise.
 */
bool Anubis::GL::UploadTextureDataToGPULegacy(GLuint& uiTextureID, const SImageData& sImageData, GLenum eTextureTarget, bool bGenMipMaps, GLenum sourceType)
{
	// 1. Immutable Storage requires a fresh ID if we are re-loading
	if (!CreateGLTexture(uiTextureID, eTextureTarget))
	{
		syserr("Failed to create texture for Legacy upload!");
		return (false);
	}

	glBindTexture(eTextureTarget, uiTextureID);

	// 2. Calculate Mip Levels (In Legacy, we don't pre-allocate levels, but we need to know if we want them)
	bool bUseMips = bGenMipMaps && sImageData.iWidth > 1;

	// 3. Determine Formats
	GLenum internalFormat, pixelFormat;
	bool bIsFloat = (sourceType == GL_FLOAT);

	GetGLTextureFormats(sImageData.iChannels, internalFormat, pixelFormat, bIsFloat);

	// 4. Upload Data (Mutable Storage)
	// Note: Legacy uses glTexImage2D. The '0' is the base mip level.
	glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
	glTexImage2D(eTextureTarget, 0, internalFormat, sImageData.iWidth, sImageData.iHeight, 0, pixelFormat, sourceType, sImageData.pData);

	// 5. Set Parameters (Using target-based functions)
	glTexParameteri(eTextureTarget, GL_TEXTURE_MIN_FILTER, bUseMips ? GL_LINEAR_MIPMAP_LINEAR : GL_LINEAR);
	glTexParameteri(eTextureTarget, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
	glTexParameteri(eTextureTarget, GL_TEXTURE_WRAP_S, GL_REPEAT);
	glTexParameteri(eTextureTarget, GL_TEXTURE_WRAP_T, GL_REPEAT);

	// 6. Handle Swizzle (If 1-channel)
	if (sImageData.iChannels == 1)
	{
		GLint greySwizzle[] = { GL_RED, GL_RED, GL_RED, GL_ONE };
		glTexParameteriv(eTextureTarget, GL_TEXTURE_SWIZZLE_RGBA, greySwizzle);
	}

	// 7. Generate Mipmaps if needed
	if (bUseMips && sImageData.pData)
	{
		glGenerateMipmap(eTextureTarget);
	}

	// 8. Unbind to avoid accidental state changes elsewhere
	glBindTexture(eTextureTarget, 0);

	return (true);
}

Anubis::GL::STextureFormat Anubis::GL::GetTextureFormats(GLint channels, GLenum* internal, GLenum* pixel, bool bIsFloat)
{
	Anubis::GL::STextureFormat texForm = { bIsFloat ? GL_RGBA32F : GL_RGBA8, GL_RGBA };
	switch (channels)
	{
	case 1:
		texForm.internal = bIsFloat ? GL_R32F : GL_R8;
		texForm.pixel = GL_RED;
		break;
	case 2:
		texForm.internal = bIsFloat ? GL_RG32F : GL_RG8;
		texForm.pixel = GL_RG;
		break;
	case 3:
		texForm.internal = bIsFloat ? GL_RGB32F : GL_RGB8;
		texForm.pixel = GL_RGB;  break;
	case 4:
		texForm.internal = bIsFloat ? GL_RGBA32F : GL_RGBA8;
		texForm.pixel = GL_RGBA; break;

	default:
		syslog("Format not implemented: {} channels", channels);
		texForm.internal = bIsFloat ? GL_RGBA32F : GL_RGBA8;
		texForm.pixel = GL_RGBA;
		break;
	}

	return (texForm);
}

/**
 * @brief Maps the number of channels to OpenGL internal and pixel formats.
 *
 * @param channels Number of color channels (1-4).
 * @param internal Reference to store the internal format.
 * @param pixel Reference to store the pixel format.
 */
void Anubis::GL::GetGLTextureFormats(GLint channels, GLenum& internal, GLenum& pixel, bool bIsFloat)
{
	switch (channels)
	{
	case 1:
		internal = bIsFloat ? GL_R32F : GL_R8;
		pixel = GL_RED;
		break;
	case 2:
		internal = bIsFloat ? GL_RG32F : GL_RG8;
		pixel = GL_RG;
		break;
	case 3:
		internal = bIsFloat ? GL_RGB32F : GL_RGB8;
		pixel = GL_RGB;  break;
	case 4:
		internal = bIsFloat ? GL_RGBA32F : GL_RGBA8;
		pixel = GL_RGBA; break;

	default:
		syslog("Format not implemented: {} channels", channels);
		internal = bIsFloat ? GL_RGBA32F : GL_RGBA8;
		pixel = GL_RGBA;
		break;
	}
}

/**
 * @brief Checks if the current OpenGL version is greater than or equal to the specified version.
 *
 * @param MajorVer The major version to check (e.g., 4)
 * @param MinorVer The minor version to check (e.g., 5)
 * @return true if current version >= specified version
 */
bool Anubis::GL::IsGLVersionHigher(GLint MajorVer, GLint MinorVer)
{
	static GLint glMajorVersion = 0;
	static GLint glMinorVersion = 0;

	// Only query once for performance
	if (glMajorVersion == 0)
	{
		glGetIntegerv(GL_MAJOR_VERSION, &glMajorVersion);
		glGetIntegerv(GL_MINOR_VERSION, &glMinorVersion);
	}

	// Check major version first
	if (glMajorVersion > MajorVer)
	{
		return true;
	}

	// Same major version, check minor
	if (glMajorVersion == MajorVer && glMinorVersion >= MinorVer)
	{
		return true;
	}

	return false;
}

